/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PostOfferRouteImport } from './routes/post-offer'
import { Route as PostListingRouteImport } from './routes/post-listing'
import { Route as OrderBookRouteImport } from './routes/order-book'
import { Route as MyThreadsRouteImport } from './routes/my-threads'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as EscrowRouteImport } from './routes/escrow'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as TradeIdRouteImport } from './routes/trade.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OfferIdRouteImport } from './routes/offer.$id'
import { Route as DisputesIdRouteImport } from './routes/disputes.$id'
import { Route as ApiPaymentMetadataRouteImport } from './routes/api/payment-metadata'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksReconcileRouteImport } from './routes/api/public/hooks/reconcile'
import { Route as ApiPublicHooksBtcpayRouteImport } from './routes/api/public/hooks/btcpay'
import { Route as ApiPublicHooksBtcConfirmPollRouteImport } from './routes/api/public/hooks/btc-confirm-poll'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PostOfferRoute = PostOfferRouteImport.update({
  id: '/post-offer',
  path: '/post-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const PostListingRoute = PostListingRouteImport.update({
  id: '/post-listing',
  path: '/post-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderBookRoute = OrderBookRouteImport.update({
  id: '/order-book',
  path: '/order-book',
  getParentRoute: () => rootRouteImport,
} as any)
const MyThreadsRoute = MyThreadsRouteImport.update({
  id: '/my-threads',
  path: '/my-threads',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowRoute = EscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeIdRoute = TradeIdRouteImport.update({
  id: '/trade/$id',
  path: '/trade/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferIdRoute = OfferIdRouteImport.update({
  id: '/offer/$id',
  path: '/offer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesIdRoute = DisputesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DisputesRoute,
} as any)
const ApiPaymentMetadataRoute = ApiPaymentMetadataRouteImport.update({
  id: '/api/payment-metadata',
  path: '/api/payment-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReconcileRoute = ApiPublicHooksReconcileRouteImport.update({
  id: '/api/public/hooks/reconcile',
  path: '/api/public/hooks/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBtcpayRoute = ApiPublicHooksBtcpayRouteImport.update({
  id: '/api/public/hooks/btcpay',
  path: '/api/public/hooks/btcpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBtcConfirmPollRoute =
  ApiPublicHooksBtcConfirmPollRouteImport.update({
    id: '/api/public/hooks/btc-confirm-poll',
    path: '/api/public/hooks/btc-confirm-poll',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/disputes': typeof DisputesRouteWithChildren
  '/escrow': typeof EscrowRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-threads': typeof MyThreadsRoute
  '/order-book': typeof OrderBookRoute
  '/post-listing': typeof PostListingRoute
  '/post-offer': typeof PostOfferRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRoute
  '/api/payment-metadata': typeof ApiPaymentMetadataRoute
  '/disputes/$id': typeof DisputesIdRoute
  '/offer/$id': typeof OfferIdRoute
  '/product/$id': typeof ProductIdRoute
  '/trade/$id': typeof TradeIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/public/hooks/btc-confirm-poll': typeof ApiPublicHooksBtcConfirmPollRoute
  '/api/public/hooks/btcpay': typeof ApiPublicHooksBtcpayRoute
  '/api/public/hooks/reconcile': typeof ApiPublicHooksReconcileRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/disputes': typeof DisputesRouteWithChildren
  '/escrow': typeof EscrowRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-threads': typeof MyThreadsRoute
  '/order-book': typeof OrderBookRoute
  '/post-listing': typeof PostListingRoute
  '/post-offer': typeof PostOfferRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRoute
  '/api/payment-metadata': typeof ApiPaymentMetadataRoute
  '/disputes/$id': typeof DisputesIdRoute
  '/offer/$id': typeof OfferIdRoute
  '/product/$id': typeof ProductIdRoute
  '/trade/$id': typeof TradeIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/public/hooks/btc-confirm-poll': typeof ApiPublicHooksBtcConfirmPollRoute
  '/api/public/hooks/btcpay': typeof ApiPublicHooksBtcpayRoute
  '/api/public/hooks/reconcile': typeof ApiPublicHooksReconcileRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/disputes': typeof DisputesRouteWithChildren
  '/escrow': typeof EscrowRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-threads': typeof MyThreadsRoute
  '/order-book': typeof OrderBookRoute
  '/post-listing': typeof PostListingRoute
  '/post-offer': typeof PostOfferRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRoute
  '/api/payment-metadata': typeof ApiPaymentMetadataRoute
  '/disputes/$id': typeof DisputesIdRoute
  '/offer/$id': typeof OfferIdRoute
  '/product/$id': typeof ProductIdRoute
  '/trade/$id': typeof TradeIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/public/hooks/btc-confirm-poll': typeof ApiPublicHooksBtcConfirmPollRoute
  '/api/public/hooks/btcpay': typeof ApiPublicHooksBtcpayRoute
  '/api/public/hooks/reconcile': typeof ApiPublicHooksReconcileRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/disputes'
    | '/escrow'
    | '/marketplace'
    | '/my-threads'
    | '/order-book'
    | '/post-listing'
    | '/post-offer'
    | '/settings'
    | '/trades'
    | '/transactions'
    | '/wallet'
    | '/api/payment-metadata'
    | '/disputes/$id'
    | '/offer/$id'
    | '/product/$id'
    | '/trade/$id'
    | '/u/$userId'
    | '/api/public/hooks/btc-confirm-poll'
    | '/api/public/hooks/btcpay'
    | '/api/public/hooks/reconcile'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/disputes'
    | '/escrow'
    | '/marketplace'
    | '/my-threads'
    | '/order-book'
    | '/post-listing'
    | '/post-offer'
    | '/settings'
    | '/trades'
    | '/transactions'
    | '/wallet'
    | '/api/payment-metadata'
    | '/disputes/$id'
    | '/offer/$id'
    | '/product/$id'
    | '/trade/$id'
    | '/u/$userId'
    | '/api/public/hooks/btc-confirm-poll'
    | '/api/public/hooks/btcpay'
    | '/api/public/hooks/reconcile'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/disputes'
    | '/escrow'
    | '/marketplace'
    | '/my-threads'
    | '/order-book'
    | '/post-listing'
    | '/post-offer'
    | '/settings'
    | '/trades'
    | '/transactions'
    | '/wallet'
    | '/api/payment-metadata'
    | '/disputes/$id'
    | '/offer/$id'
    | '/product/$id'
    | '/trade/$id'
    | '/u/$userId'
    | '/api/public/hooks/btc-confirm-poll'
    | '/api/public/hooks/btcpay'
    | '/api/public/hooks/reconcile'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DisputesRoute: typeof DisputesRouteWithChildren
  EscrowRoute: typeof EscrowRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MyThreadsRoute: typeof MyThreadsRoute
  OrderBookRoute: typeof OrderBookRoute
  PostListingRoute: typeof PostListingRoute
  PostOfferRoute: typeof PostOfferRoute
  SettingsRoute: typeof SettingsRoute
  TradesRoute: typeof TradesRoute
  TransactionsRoute: typeof TransactionsRoute
  WalletRoute: typeof WalletRoute
  ApiPaymentMetadataRoute: typeof ApiPaymentMetadataRoute
  OfferIdRoute: typeof OfferIdRoute
  ProductIdRoute: typeof ProductIdRoute
  TradeIdRoute: typeof TradeIdRoute
  UUserIdRoute: typeof UUserIdRoute
  ApiPublicHooksBtcConfirmPollRoute: typeof ApiPublicHooksBtcConfirmPollRoute
  ApiPublicHooksBtcpayRoute: typeof ApiPublicHooksBtcpayRoute
  ApiPublicHooksReconcileRoute: typeof ApiPublicHooksReconcileRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-offer': {
      id: '/post-offer'
      path: '/post-offer'
      fullPath: '/post-offer'
      preLoaderRoute: typeof PostOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-listing': {
      id: '/post-listing'
      path: '/post-listing'
      fullPath: '/post-listing'
      preLoaderRoute: typeof PostListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-book': {
      id: '/order-book'
      path: '/order-book'
      fullPath: '/order-book'
      preLoaderRoute: typeof OrderBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-threads': {
      id: '/my-threads'
      path: '/my-threads'
      fullPath: '/my-threads'
      preLoaderRoute: typeof MyThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrow': {
      id: '/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof EscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$id': {
      id: '/trade/$id'
      path: '/trade/$id'
      fullPath: '/trade/$id'
      preLoaderRoute: typeof TradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/$id': {
      id: '/offer/$id'
      path: '/offer/$id'
      fullPath: '/offer/$id'
      preLoaderRoute: typeof OfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes/$id': {
      id: '/disputes/$id'
      path: '/$id'
      fullPath: '/disputes/$id'
      preLoaderRoute: typeof DisputesIdRouteImport
      parentRoute: typeof DisputesRoute
    }
    '/api/payment-metadata': {
      id: '/api/payment-metadata'
      path: '/api/payment-metadata'
      fullPath: '/api/payment-metadata'
      preLoaderRoute: typeof ApiPaymentMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reconcile': {
      id: '/api/public/hooks/reconcile'
      path: '/api/public/hooks/reconcile'
      fullPath: '/api/public/hooks/reconcile'
      preLoaderRoute: typeof ApiPublicHooksReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/btcpay': {
      id: '/api/public/hooks/btcpay'
      path: '/api/public/hooks/btcpay'
      fullPath: '/api/public/hooks/btcpay'
      preLoaderRoute: typeof ApiPublicHooksBtcpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/btc-confirm-poll': {
      id: '/api/public/hooks/btc-confirm-poll'
      path: '/api/public/hooks/btc-confirm-poll'
      fullPath: '/api/public/hooks/btc-confirm-poll'
      preLoaderRoute: typeof ApiPublicHooksBtcConfirmPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DisputesRouteChildren {
  DisputesIdRoute: typeof DisputesIdRoute
}

const DisputesRouteChildren: DisputesRouteChildren = {
  DisputesIdRoute: DisputesIdRoute,
}

const DisputesRouteWithChildren = DisputesRoute._addFileChildren(
  DisputesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DisputesRoute: DisputesRouteWithChildren,
  EscrowRoute: EscrowRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyThreadsRoute: MyThreadsRoute,
  OrderBookRoute: OrderBookRoute,
  PostListingRoute: PostListingRoute,
  PostOfferRoute: PostOfferRoute,
  SettingsRoute: SettingsRoute,
  TradesRoute: TradesRoute,
  TransactionsRoute: TransactionsRoute,
  WalletRoute: WalletRoute,
  ApiPaymentMetadataRoute: ApiPaymentMetadataRoute,
  OfferIdRoute: OfferIdRoute,
  ProductIdRoute: ProductIdRoute,
  TradeIdRoute: TradeIdRoute,
  UUserIdRoute: UUserIdRoute,
  ApiPublicHooksBtcConfirmPollRoute: ApiPublicHooksBtcConfirmPollRoute,
  ApiPublicHooksBtcpayRoute: ApiPublicHooksBtcpayRoute,
  ApiPublicHooksReconcileRoute: ApiPublicHooksReconcileRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
